# Generated by Django 5.1.4 on 2025-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_lawyers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'lawyer'}, related_name='secretaries', to='profiles.profile'),
        ),
    ]
