# Generated by Django 5.1.4 on 2025-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceareas', '0001_initial'),
        ('profiles', '0002_profile_assigned_lawyers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='practice_areas',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='practiceareas.practicearea'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('lawyer', 'Lawyer'), ('client', 'Client'), ('secretary', 'Secretary')], default='client', max_length=20),
        ),
    ]
