# Generated by Django 5.1.4 on 2025-10-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_blogpost_content_en_blogpost_content_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_es',
            field=models.TextField(blank=True),
        ),
    ]
