# Generated by Django 5.1.4 on 2025-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_testimonial_content_en_testimonial_content_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
