# Generated by Django 5.1.4 on 2025-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_blogpost_active_testimonial_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_bg', models.ImageField(blank=True, null=True, upload_to='portal/backgrounds/')),
                ('about_bg', models.ImageField(blank=True, null=True, upload_to='portal/backgrounds/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
