# Generated by Django 5.1.4 on 2025-10-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceareas', '0002_seed_practice_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='practiceareas/'),
        ),
    ]
